### ISSUE TITLE
If I want to send a reject reason to the user, how would I do that?

### ISSUE THREAD

**Issue by HenkPoley** [afterlogic/aurora-module-ldap-auth#1]
I suppose there is a facility to send back more than true/false from an authentication module like this. But I'm sort of missing it between all the code.

**Comment by afterlogic-support** [comment]
You can throw an exception, with a custom message supplied, something like this:
```php
throw new \Aurora\System\Exceptions\ApiException(\Aurora\System\Notifications::AccountExists, null, "Some text here");
```

**Comment by HenkPoley** [comment]
Made some typehints for the ApiException https://github.com/afterlogic/aurora-framework/pull/7

**Comment by HenkPoley** [comment]
Hmm, finally had some time to try it in my code. But the message doesn't quite bubble up through the API.

I put the ApiException throw at the top of `public function onBeforeLogin($aArgs)`: https://github.com/afterlogic/aurora-module-ldap-auth/issues/1#issuecomment-782095710 (I see this function is not used in Afterlogic's LDAP module, but we have it as a `$this->subscribeEvent('LoginArguments', array($this, 'onBeforeLogin'));` in `init()`)

> Edit: I see we hacked that into \Aurora\Modules\Core\Module::Authenticate() as a broadcastEvent() )

And the same with a slightly different text in `public function onLogin($aArgs, &$mResult)`.

?/Api/ response is:

```
{
   "AuthenticatedUserId":0,
   "@Time":0.3229,
   "SubscriptionsResult":null,
   "@TimeApiInit":0.2862,
   "ErrorCode":102,
   "Module":""
}
```

**Comment by afterlogic-support** [comment]
We suggest to add logging with `\Aurora\System\Api::Log` where exception is thrown, to make sure that the code actually gets executed there.

**Comment by HenkPoley** [comment]
I found the spot where the ApiException was eaten 😅.

Where we added the `broadcastEvent('LoginArguments', $aArgs)`, we also did a try-catch(\Exception $e) (_catch all_).

Not entirely sure why the decision was made to bypass the 'normal' authentication module interface (well, there is non actually specified in code), but I think I can get our required changes working now.

Thanks for the help 🙂
